networks:
  services-network:
    driver: bridge

volumes:
  postgres-data:

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    labels:
      - "ping_port=5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - services-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    labels:
      - "ping_port=8382"
    ports:
      - "8382:8382"
    depends_on:
      - database
    networks:
      - services-network

  pinger:
    build:
      context: ./pinger
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend
    networks:
      - services-network

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    depends_on:
#      - backend
#    networks:
#      - services-network